In [4]:
# NumPy is just a special type of array in python
# NumPy = Numeric Python
# Anything in NumPy has to be of the same dt

import numpy as np

# Creating 1-D array
np1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(np1)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
# Functions in NumPy

# .shape: (rows, columns)
print(np1.shape)


(10,)


In [7]:
# Create a range np1
np2 = np.arange(10) # gen 0 to 9
print(np2)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
np2 = np.arange(1, 50, 4)  # press SHIFT + TAB  to see info
print(np2)

[ 1  5  9 13 17 21 25 29 33 37 41 45 49]


In [9]:
# Create an array of zeros 
np3 = np.zeros(10)  # press SHIFT + TAB  to see info
print(np3)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [13]:
# Multidimensional array

np4 = np.full((5, 6), 5)  # press SHIFT + TAB  to see info
print(np4)

[[5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]]


In [15]:
# Converting Python list to NumPy

np5 = [1, 3, 5, 7, 9]
np6 = np.array(np5)
print(np5)
print(np6)

[1, 3, 5, 7, 9]
[1 3 5 7 9]


In [16]:
# Assessing element via indexing
print(np5[3])

7
